import type { SessionQuestion } from "../types/home";

export const sessionQuestions: SessionQuestion[] = [
  {
    id: "mood",
    label: "How are you feeling?",
    type: "single-select",
    mandatory: true,
    options: ["Chill", "Social", "Tired", "Bored", "Excited", "Calm", "Lonely"],
  },
  {
    id: "energy",
    label: "What energy do you want?",
    type: "single-select",
    mandatory: false,
    options: ["Low", "Balanced", "Fun", "Focused", "Spontaneous"],
  },
  {
    id: "goal",
    label: "What are you looking for?",
    type: "single-select",
    mandatory: true,
    options: [
      "Long-term romance",
      "Short-term romance",
      "Friends",
      "Activity buddy",
      "Study buddy",
      "Growth companion",
      "Event buddy",
      "Food buddy",
      "Chat friend",
    ],
  },
  {
    id: "companyType",
    label: "What kind of company do you want?",
    type: "single-select",
    mandatory: true,
    options: ["Listener", "Adviser", "Be Listener", "Be Adviser", "Mutual"],
  },
  {
    id: "companyFeel",
    label: "What company feels best today?",
    type: "single-select",
    mandatory: true,
    options: ["Listen", "Fun chat", "Hear story", "Small favor", "Advice", "Walk", "Do together", "Company"],
  },
  {
    id: "activities",
    label: "What activities interest you?",
    type: "multi-select",
    mandatory: true,
    options: [
      "Gaming",
      "Coffee",
      "Food",
      "Drinks",
      "Walking",
      "Study",
      "Gym",
      "Movies",
      "Concerts",
      "Events",
      "Shopping",
      "Art",
      "Hiking",
      "Board games",
      "Karaoke",
      "Clubbing",
      "Night walk",
    ],
  },
  {
    id: "vibeType",
    label: "What vibe do you want?",
    type: "single-select",
    mandatory: true,
    options: ["Chill", "Fun", "Focused", "Deep", "Active", "Creative", "Adventurous", "Low-key"],
  },
  {
    id: "relaxation",
    label: "What do you do to relax?",
    type: "single-select",
    mandatory: false,
    options: ["Series", "Games", "Music", "Walk", "Chat", "Scroll"],
  },
  {
    id: "weekend",
    label: "Ideal weekend vibe?",
    type: "single-select",
    mandatory: false,
    options: ["Home", "Explore", "Hang out", "Creative", "Task", "Small-group"],
  },
  {
    id: "moment",
    label: "Pick favorite moment",
    type: "single-select",
    mandatory: false,
    options: ["Walk", "Coffee", "Dinner", "Study", "Concert", "Chat"],
  },
  {
    id: "topicType",
    label: "Personal or Public topics?",
    type: "slider",
    mandatory: true,
    sliderMin: "Personal",
    sliderMax: "Public",
  },
  {
    id: "calmToEnergetic",
    label: "How energetic do you want to be?",
    type: "slider",
    mandatory: true,
    sliderMin: "Calm",
    sliderMax: "Energetic",
  },
  {
    id: "shareToReserve",
    label: "How much do you want to share?",
    type: "slider",
    mandatory: true,
    sliderMin: "Share",
    sliderMax: "Reserve",
  },
  {
    id: "avoid",
    label: "What to avoid today?",
    type: "multi-select",
    mandatory: false,
    options: ["Loud", "Serious", "Romantic", "Intense", "Smokers"],
  },
];
