export type ThemeId = "rose" | "sunset" | "ocean" | "midnight" | "forest" | "lavender" | "neon" | "cyber" | "pastel" | "aurora";

export interface AppTheme {
  id: ThemeId;
  name: string;
  emoji: string;
  primary: string;
  primaryLight: string;
  secondary: string;
  secondaryLight: string;
  accent: string;
  background: string;
  card: string;
  foreground: string;
  muted: string;
  mutedForeground: string;
  border: string;
  white: string;
}

export const THEMES: Record<ThemeId, AppTheme> = {
  rose: {
    id: "rose",
    name: "Rose",
    emoji: "🌹",
    primary: "#FF5376",
    primaryLight: "#FF9A76",
    secondary: "#6C5CE7",
    secondaryLight: "#A29BFE",
    accent: "#FFD1DC",
    background: "#FFF5F7",
    card: "#FFFFFF",
    foreground: "#1A1A2E",
    muted: "#FFF0F3",
    mutedForeground: "#9B8A9E",
    border: "#FFD6DE",
    white: "#FFFFFF",
  },
  sunset: {
    id: "sunset",
    name: "Sunset",
    emoji: "🌅",
    primary: "#FF6B35",
    primaryLight: "#FFB347",
    secondary: "#E84393",
    secondaryLight: "#FD79A8",
    accent: "#FFEAA7",
    background: "#FFF8F0",
    card: "#FFFFFF",
    foreground: "#2D3436",
    muted: "#FFF0E0",
    mutedForeground: "#A89F96",
    border: "#FFD5B8",
    white: "#FFFFFF",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    emoji: "🌊",
    primary: "#0984E3",
    primaryLight: "#74B9FF",
    secondary: "#6C5CE7",
    secondaryLight: "#A29BFE",
    accent: "#81ECEC",
    background: "#F0F9FF",
    card: "#FFFFFF",
    foreground: "#2D3436",
    muted: "#E8F4FD",
    mutedForeground: "#8C9EAA",
    border: "#BEE3F8",
    white: "#FFFFFF",
  },
  midnight: {
    id: "midnight",
    name: "Midnight",
    emoji: "🌙",
    primary: "#6C5CE7",
    primaryLight: "#A29BFE",
    secondary: "#E84393",
    secondaryLight: "#FD79A8",
    accent: "#74B9FF",
    background: "#1A1A2E",
    card: "#16213E",
    foreground: "#EAEAEA",
    muted: "#1F2B47",
    mutedForeground: "#7F8FA6",
    border: "#2C3A5B",
    white: "#FFFFFF",
  },
  forest: {
    id: "forest",
    name: "Forest",
    emoji: "🌿",
    primary: "#00B894",
    primaryLight: "#55EFC4",
    secondary: "#FDCB6E",
    secondaryLight: "#FFEAA7",
    accent: "#DFE6E9",
    background: "#F0FFF4",
    card: "#FFFFFF",
    foreground: "#2D3436",
    muted: "#E8F8F0",
    mutedForeground: "#8FAF9E",
    border: "#B2DFDB",
    white: "#FFFFFF",
  },
  lavender: {
    id: "lavender",
    name: "Lavender",
    emoji: "💜",
    primary: "#A855F7",
    primaryLight: "#C084FC",
    secondary: "#EC4899",
    secondaryLight: "#F472B6",
    accent: "#E0C3FC",
    background: "#FAF5FF",
    card: "#FFFFFF",
    foreground: "#1E1B2E",
    muted: "#F3E8FF",
    mutedForeground: "#A794B8",
    border: "#E9D5FF",
    white: "#FFFFFF",
  },
  // ── GenZ Themes ──────────────────────────────────────────────────
  neon: {
    id: "neon",
    name: "Neon",
    emoji: "⚡",
    primary: "#00FF87",
    primaryLight: "#00CC6A",
    secondary: "#FF00FF",
    secondaryLight: "#FF66FF",
    accent: "#00FFFF",
    background: "#0A0A1A",
    card: "#141428",
    foreground: "#E0E0FF",
    muted: "#1A1A30",
    mutedForeground: "#7F8FA6",
    border: "#2C2C5B",
    white: "#FFFFFF",
  },
  cyber: {
    id: "cyber",
    name: "Cyber",
    emoji: "🤖",
    primary: "#FF2E63",
    primaryLight: "#FF6B8A",
    secondary: "#08F7FE",
    secondaryLight: "#6BFFF7",
    accent: "#FEE440",
    background: "#0F0F23",
    card: "#1A1A35",
    foreground: "#EAEAEA",
    muted: "#1F1F40",
    mutedForeground: "#7F8FA6",
    border: "#2C2C5B",
    white: "#FFFFFF",
  },
  pastel: {
    id: "pastel",
    name: "Pastel",
    emoji: "🧁",
    primary: "#FFB3BA",
    primaryLight: "#FFD1D8",
    secondary: "#BAFFC9",
    secondaryLight: "#D4FFE0",
    accent: "#BAE1FF",
    background: "#FFF5F5",
    card: "#FFFFFF",
    foreground: "#4A4A6A",
    muted: "#FFF0F0",
    mutedForeground: "#A0A0B0",
    border: "#FFD6DE",
    white: "#FFFFFF",
  },
  aurora: {
    id: "aurora",
    name: "Aurora",
    emoji: "🌌",
    primary: "#667EEA",
    primaryLight: "#764BA2",
    secondary: "#00C9FF",
    secondaryLight: "#92FE9D",
    accent: "#F093FB",
    background: "#F0F4FF",
    card: "#FFFFFF",
    foreground: "#2D3748",
    muted: "#EDF2F7",
    mutedForeground: "#A0AEC0",
    border: "#BEE3F8",
    white: "#FFFFFF",
  },
};

export const DEFAULT_THEME_ID: ThemeId = "rose";
